services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - UVICORN_PORT=8000
      - UVICORN_HOST=0.0.0.0
    ports:
      - 8000:8000
    command: uvicorn backend.server.main:app 
