services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - FLASK_ENV=production
    ports:
      - 8000:8000
    command: gunicorn backend.server.main:app 
