services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:

      - PORT=8000
      - HOST=0.0.0.0
      - FLASK_ENV=production
    ports:
      - 8000:8000
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/sqlite:/app/sqlite
    command: gunicorn backend.server.wsgi:app --access-logfile /app/logs/access.log --error-logfile /app/logs/error.log 



volumes:
  logs:
