services:

  backend: 
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/sqlite:/app/sqlite
    command: sh ./prod_entrypoint.sh

