services:

  backend: 
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - APP_MODE=PROD
    expose:
      - 8000
    networks:
      - webnet
    volumes:
      - ./backend/logs:/server/logs
      - ./backend/sqlite:/server/sqlite
    command: sh ./prod_entrypoint.sh

  web:
    depends_on:
      - backend
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
      args:
        API_VERSION: '0.0'
        BASE_URL: http://localhost:4000/api
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - webnet

  nginx:
    depends_on:
      - backend
    build:
      context: services
      dockerfile: Dockerfile
    ports:
      - 4000:80
    networks:
      - webnet
    

networks:
  webnet: